spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    enabled: true
#    path: /swagger-ui.html

logging:
  level:
    root: info
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","thread":"%t","logger":"%c","message":"%m"}%n'

management:
  endpoints:
    web:
      exposure:
        include: health, info
